### ISSUE TITLE
Start building Tibber Binding for Openhab

### ISSUE THREAD

**Issue by Ontrackx** [Ontrackx/Tibber-Binding#1]
https://developer.tibber.com/docs/guides/calling-api

Athom homey source if that helps : https://github.com/slasktrat/com.tibber/tree/6c935ccd2239a3f5e5f2bdc677fb8e100423a217

**Comment by Danielhiversen** [comment]
Python library that Home Assistant uses might be useful: https://github.com/Danielhiversen/pyTibber
